# Site settings
title: andersonribeiro.net
email: dimrsilva@gmail.com
description: Um blog sobre telas pretas e códigos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andersonribeiro.net" # the base hostname & protocol for your site
# twitter_username: dimribeiro
github_username:  dimrsilva

# Build settings
markdown: kramdown
